# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1bf1152a-1973-46e9-b758-e0c69fdaf53f";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."NIXROOT".device = "/dev/disk/by-uuid/92e24162-7961-4335-866b-6b197eb95852";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1bf1152a-1973-46e9-b758-e0c69fdaf53f";
      fsType = "btrfs";
      options = [ "subvol=@HOME" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/1bf1152a-1973-46e9-b758-e0c69fdaf53f";
      fsType = "btrfs";
      options = [ "subvol=.snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B3AB-CAA7";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1a687105-f03d-467a-928b-833cd9d6f686"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
