# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/NIXROOT";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."NIXROOT".device = "/dev/disk/by-uuid/55bf544e-1941-428a-81da-e5d14e3c6dcb";

  fileSystems."/home" =
    { device = "/dev/mapper/NIXROOT";
      fsType = "btrfs";
      options = [ "subvol=@HOME" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/mapper/NIXROOT";
      fsType = "btrfs";
      options = [ "subvol=.snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5BEB-39B8";
      fsType = "vfat";
    };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
