complete_from_path = true
ctrlc_exit = false
disable_table_indexes = false
filesize_format = "B"
nonzero_exit_errors = true
path = [
    "/home/gnus/bin", 
    "/home/gnus/.cargo/bin", 
    "//home/gnus/.local/bin", 
    "//home/gnus/.config/repos/dotfiles/bin/", 
    "/run/wrappers/bin", 
    "/home/gnus/.nix-profile/bin", 
    "/etc/profiles/per-user/gnus/bin", 
    "/nix/var/nix/profiles/default/bin", 
    "/run/current-system/sw/bin"
    ]
pivot_mode = "auto"
rm_always_trash = true
skip_welcome_message = true
startup = [
    #shell aliases BEGIN
    "alias :q = exit",
    "alias ll = ls -la",
    "alias vim = nvim",
    "alias vi = nvim",
    #shell aliases END

    #git aliases BEGIN
    "def gl [] {git log --pretty=%h»¦«%s»¦«%aN»¦«%aE»¦«%aD -n 5 | lines | split column »¦« hash message user email date}",
    #git aliases END

    #other aliases BEGIN
    "def nuver [] {version | pivot key value}",
    #other aliases BEGIN
    ]
table_mode = "compact"

[color_config]
header_align = "l"
header_bold = true
header_color = "c"
index_color = "rd"
leading_trailing_space_bg = "white"
primitive_binary = "cyan"
primitive_boolean = "green"
primitive_columnpath = "cyan"
primitive_date = "ru"
primitive_decimal = "red"
primitive_duration = "blue"
primitive_filesize = "ur"
primitive_int = "green"
primitive_line = "yellow"
primitive_path = "yellow"
primitive_pattern = "white"
primitive_range = "purple"
primitive_string = "pb"
separator_color = "purple"

[line_editor]
auto_add_history = true
bell_style = "none"
color_mode = "enabled"
completion_prompt_limit = 100
completion_type = "circular"
edit_mode = "vi"
history_duplicates = "ignoreconsecutive"
history_ignore_space = false
keyseq_timeout_ms = 500
max_history_size = 100000
tab_stop = 4

[textview]
colored_output = true
grid = false
header = true
line_numbers = true
pager = "bat"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 4
term_width = "default"
theme = "TwoDark"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "NoWrapping"
